// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgresRepo

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int32
	Name      string
	Pwd       string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
